services:
  frontend:
    image: tapnisu/leshapomogi.ru:main
    ports:
      - "8000:8000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--cleanup"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
