services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.websecure.address=:443"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=aleksei@tapni.su"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  frontend:
    image: tapnisu/leshapomogi.ru:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.leshapomogi.rule=Host(`leshapomogi.ru`) || Host(`www.leshapomogi.ru`) || Host(`xn--80agpjglbf3f6d.xn--p1ai`) || Host(`www.xn--80agpjglbf3f6d.xn--p1ai`) || Host(`xn--80ageolinbg2g.xn--p1ai`) || Host(`www.xn--80ageolinbg2g.xn--p1ai`)
      - traefik.http.routers.leshapomogi.entrypoints=websecure
      - traefik.http.routers.leshapomogi.tls.certresolver=myresolver

      - traefik.http.middlewares.leshapomogiredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.leshapomogiredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.leshapomogi.middlewares=leshapomogiredirect

      - com.centurylinklabs.watchtower.enable=true
    deploy:
      mode: replicated
      replicas: 3
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  letsencrypt:
