version: "3"

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.websecure.adress=:443"

      - "--entrypoints.web.adress=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=aleksei@tapni.su"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      - "traefik.http.middlewares.secondary-domain1.redirectregex.regex=^http://лёшапомоги.рф/(.*)"
      - "traefik.http.middlewares.secondary-domain1.redirectregex.replacement=http://leshapomogi.ru/$${1}"

      - "traefik.http.middlewares.secondary-domain1.redirectregex.regex=^http://лешапомоги.рф/(.*)"
      - "traefik.http.middlewares.secondary-domain1.redirectregex.replacement=http://leshapomogi.ru/$${1}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  frontend:
    image: tapnisu/leshapomogi.ru:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guestbook.rule=Host(`leshapomogi.ru`)"
      - "traefik.http.routers.guestbook.entrypoints=websecure"
      - "traefik.http.routers.guestbook.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 3
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  letsencrypt:
